# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('account_type', models.CharField(choices=[('C', 'Checking'), ('S', 'Saving')], max_length=1)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'money_bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cat_type', models.SmallIntegerField(choices=[(-1, 'Expense'), (1, 'Income')])),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='money.Category')),
            ],
            options={
                'db_table': 'money_categories',
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('opened_date', models.DateField()),
            ],
            options={
                'db_table': 'money_credit_accounts',
            },
        ),
        migrations.CreateModel(
            name='IncomeStmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.CharField(max_length=128)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.BankAccount')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Category')),
            ],
            options={
                'db_table': 'money_income_stmts',
            },
        ),
        migrations.CreateModel(
            name='StmtBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('due_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.CreditAccount')),
            ],
            options={
                'db_table': 'money_stmt_balances',
            },
        ),
        migrations.CreateModel(
            name='StmtDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('note', models.CharField(max_length=128)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.StmtBalance')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Category')),
            ],
            options={
                'db_table': 'money_stmt_details',
            },
        ),
    ]
