# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stmtdetail',
            name='tx_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set([('name', 'account_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('name', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='creditaccount',
            unique_together=set([('name', 'opened_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='stmtbalance',
            unique_together=set([('account', 'closing_date')]),
        ),
    ]
