# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20170712_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='closed_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
