# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20170712_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditaccount',
            options={'ordering': ['closed_date', 'name', 'opened_date']},
        ),
        migrations.AlterModelOptions(
            name='stmtbalance',
            options={'ordering': ['closing_date', 'account']},
        ),
        migrations.AlterField(
            model_name='stmtdetail',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
