# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20170721_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.SmallIntegerField(choices=[(-1, 'Expense'), (0, 'Transfer/Payment'), (1, 'Income')]),
        ),
        migrations.AlterField(
            model_name='incomestmt',
            name='linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='money.CreditAccount'),
        ),
        migrations.AlterField(
            model_name='incomestmt',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
