# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_auto_20170721_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestmt',
            name='tx_year',
            field=models.SmallIntegerField(default=2017),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stmtbalance',
            name='closing_year',
            field=models.SmallIntegerField(default=2017),
            preserve_default=False,
        ),
    ]
