# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 07:25
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_auto_20170722_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#00FFFF', max_length=18),
        ),
        migrations.AddField(
            model_name='category',
            name='note',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
