# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 05:40
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_auto_20170724_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualgoal',
            name='target_saving',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#66CDAA', max_length=18),
        ),
    ]
